# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/hartm391/EE_4301/Labs/07/project_7/project_7.cache/wt [current_project]
set_property parent.project_path C:/Users/hartm391/EE_4301/Labs/07/project_7/project_7.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/hartm391/EE_4301/Labs/07/project_7/project_7.srcs/sources_1/new/block_ram.v
  C:/Users/hartm391/EE_4301/Labs/07/project_7/project_7.srcs/sources_1/new/lookup.v
  C:/Users/hartm391/EE_4301/Labs/07/project_7/project_7.srcs/sources_1/new/clock_divider.v
  C:/Users/hartm391/EE_4301/Labs/07/project_7/project_7.srcs/sources_1/new/Button_Trigger.v
  C:/Users/hartm391/EE_4301/Labs/07/project_7/project_7.srcs/sources_1/new/Text_Input_Output.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/hartm391/EE_4301/Labs/07/project_7/project_7.srcs/constrs_1/new/Text_Input_Output.xdc
set_property used_in_implementation false [get_files C:/Users/hartm391/EE_4301/Labs/07/project_7/project_7.srcs/constrs_1/new/Text_Input_Output.xdc]


synth_design -top Text_Input_Output -part xc7a35tcpg236-1


write_checkpoint -force -noxdef Text_Input_Output.dcp

catch { report_utilization -file Text_Input_Output_utilization_synth.rpt -pb Text_Input_Output_utilization_synth.pb }
